#!/bin/bash
# ============================================================
# RouteIQ Setup Wizard
# Run this once: bash setup.sh
# ============================================================

set -e

BOLD="\033[1m"
GREEN="\033[32m"
YELLOW="\033[33m"
CYAN="\033[36m"
RED="\033[31m"
RESET="\033[0m"

clear
echo ""
echo -e "${BOLD}${CYAN}╔══════════════════════════════════════╗${RESET}"
echo -e "${BOLD}${CYAN}║        RouteIQ Setup Wizard          ║${RESET}"
echo -e "${BOLD}${CYAN}╚══════════════════════════════════════╝${RESET}"
echo ""
echo -e "This wizard will configure your app and start it up."
echo -e "You'll need to open ${BOLD}3 browser tabs${RESET} to get your keys."
echo ""
echo -e "${YELLOW}Press Enter to begin...${RESET}"
read -r

# ── Helper functions ──────────────────────────────────────────────────────────

ask() {
  local var_name="$1"
  local prompt="$2"
  local secret="$3"
  local value=""
  echo ""
  echo -e "${BOLD}$prompt${RESET}"
  if [ "$secret" = "secret" ]; then
    read -r -s value
    echo ""
  else
    read -r value
  fi
  eval "$var_name='$value'"
}

ask_multiline() {
  local var_name="$1"
  local prompt="$2"
  echo ""
  echo -e "${BOLD}$prompt${RESET}"
  echo -e "${YELLOW}(Paste your JSON, then press Enter, then type END and press Enter)${RESET}"
  local lines=""
  while IFS= read -r line; do
    [ "$line" = "END" ] && break
    lines="$lines$line"
  done
  # Minify to single line (remove whitespace between JSON tokens)
  local minified
  minified=$(echo "$lines" | python3 -c "import sys,json; print(json.dumps(json.load(sys.stdin)))" 2>/dev/null || echo "$lines")
  eval "$var_name='$minified'"
}

write_env() {
  cat > .env <<EOF
# RouteIQ Environment — generated by setup.sh
# Do not commit this file to git.

# Google Maps (covers Maps JS, Geocoding, Roads, Routes, Distance Matrix)
GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}

# Firebase (client-side)
NEXT_PUBLIC_FIREBASE_API_KEY=${FB_API_KEY}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${FB_AUTH_DOMAIN}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${FB_PROJECT_ID}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${FB_STORAGE_BUCKET}
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${FB_SENDER_ID}
NEXT_PUBLIC_FIREBASE_APP_ID=${FB_APP_ID}

# Firebase Admin (server-side)
FIREBASE_SERVICE_ACCOUNT=${FB_SERVICE_ACCOUNT}

# FieldRoutes
FIELDROUTES_AUTH_KEY=${FR_AUTH_KEY}
FIELDROUTES_SECRET_KEY=${FR_SECRET_KEY}
FIELDROUTES_BASE_URL=https://api.fieldroutes.com

# OSRM (leave as-is for public demo server)
OSRM_BASE_URL=http://router.project-osrm.org
EOF
}

# ══════════════════════════════════════════════════════════════
# STEP 1 — Google Maps API Key
# ══════════════════════════════════════════════════════════════
clear
echo ""
echo -e "${BOLD}${CYAN}── Step 1 of 3: Google Maps API Key ──────────────────────${RESET}"
echo ""
echo -e "1. Open this URL in your browser:"
echo -e "   ${BOLD}https://console.cloud.google.com/apis/dashboard${RESET}"
echo ""
echo -e "2. Create a new project called ${BOLD}RouteIQ${RESET} (top-left dropdown)"
echo ""
echo -e "3. Enable these 6 APIs (search each one and click Enable):"
echo -e "   • Maps JavaScript API"
echo -e "   • Geocoding API"
echo -e "   • Roads API"
echo -e "   • Routes API"
echo -e "   • Distance Matrix API"
echo -e "   • Maps Embed API"
echo ""
echo -e "4. Go to ${BOLD}APIs & Services → Credentials → + Create Credentials → API Key${RESET}"
echo -e "   Copy the key shown."
echo ""
ask GOOGLE_MAPS_API_KEY "Paste your Google Maps API key here:"

# ══════════════════════════════════════════════════════════════
# STEP 2 — Firebase
# ══════════════════════════════════════════════════════════════
clear
echo ""
echo -e "${BOLD}${CYAN}── Step 2 of 3: Firebase ─────────────────────────────────${RESET}"
echo ""
echo -e "1. Open: ${BOLD}https://console.firebase.google.com${RESET}"
echo -e "   → Add project → Name it ${BOLD}RouteIQ${RESET} → Create"
echo ""
echo -e "2. Inside your project, click the ${BOLD}</> (Web)${RESET} icon to register a web app"
echo -e "   → Name: routeiq → Register"
echo -e "   You'll see a firebaseConfig block — keep this page open"
echo ""
echo -e "3. Enable Auth: ${BOLD}Authentication → Get started → Email/Password → Enable${RESET}"
echo ""
echo -e "4. Enable Database: ${BOLD}Firestore Database → Create database → Production mode${RESET}"
echo -e "   Pick any region → Done"
echo ""
echo -e "${YELLOW}Press Enter when done, then paste each value from your firebaseConfig...${RESET}"
read -r

echo ""
echo -e "From your firebaseConfig block, paste each value:"
echo -e "${YELLOW}(Example: AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)${RESET}"

ask FB_API_KEY   "apiKey:"
ask FB_AUTH_DOMAIN "authDomain: (e.g. routeiq-12345.firebaseapp.com)"
ask FB_PROJECT_ID  "projectId: (e.g. routeiq-12345)"
ask FB_STORAGE_BUCKET "storageBucket: (e.g. routeiq-12345.appspot.com)"
ask FB_SENDER_ID   "messagingSenderId: (numbers only)"
ask FB_APP_ID      "appId: (starts with 1:)"

echo ""
echo -e "${BOLD}Now get your service account key:${RESET}"
echo -e "1. Firebase → ⚙️ Project Settings → Service Accounts"
echo -e "2. Click ${BOLD}Generate new private key${RESET} → Generate key"
echo -e "3. It downloads a .json file to your Downloads folder"
echo ""
echo -e "${BOLD}Drag the downloaded .json file from Finder into this terminal window,${RESET}"
echo -e "then press Enter:"
read -r FB_SERVICE_ACCOUNT_PATH
# Strip any quotes or whitespace from drag-and-drop
FB_SERVICE_ACCOUNT_PATH=$(echo "$FB_SERVICE_ACCOUNT_PATH" | tr -d "'" | xargs)
if [ ! -f "$FB_SERVICE_ACCOUNT_PATH" ]; then
  echo -e "${RED}File not found: $FB_SERVICE_ACCOUNT_PATH${RESET}"
  echo -e "Enter the full path manually (e.g. /Users/jalenbrown/Downloads/routeiq-xxxx.json):"
  read -r FB_SERVICE_ACCOUNT_PATH
  FB_SERVICE_ACCOUNT_PATH=$(echo "$FB_SERVICE_ACCOUNT_PATH" | tr -d "'" | xargs)
fi
FB_SERVICE_ACCOUNT=$(python3 -c "import sys,json; print(json.dumps(json.load(open('$FB_SERVICE_ACCOUNT_PATH'))))" 2>/dev/null)
if [ -z "$FB_SERVICE_ACCOUNT" ]; then
  echo -e "${RED}Could not read the file. Check the path and try again.${RESET}"
  exit 1
fi
echo -e "${GREEN}✓ Service account loaded${RESET}"

# ══════════════════════════════════════════════════════════════
# STEP 3 — FieldRoutes
# ══════════════════════════════════════════════════════════════
clear
echo ""
echo -e "${BOLD}${CYAN}── Step 3 of 3: FieldRoutes Keys ─────────────────────────${RESET}"
echo ""
echo -e "Your FieldRoutes API credentials. These are in your FieldRoutes account"
echo -e "under ${BOLD}Settings → API Access${RESET}."
echo ""
ask FR_AUTH_KEY   "FieldRoutes Auth Key:"   secret
ask FR_SECRET_KEY "FieldRoutes Secret Key:" secret

# ══════════════════════════════════════════════════════════════
# Write .env and start
# ══════════════════════════════════════════════════════════════
clear
echo ""
echo -e "${BOLD}${GREEN}✓ All keys collected — writing .env file...${RESET}"
write_env
echo -e "${GREEN}✓ .env written${RESET}"
echo ""
echo -e "${BOLD}Starting RouteIQ...${RESET}"
echo -e "(This builds the Docker containers — takes about 2 minutes the first time)"
echo ""
docker compose up --build -d

echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════╗${RESET}"
echo -e "${BOLD}${GREEN}║   RouteIQ is starting up!            ║${RESET}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════╝${RESET}"
echo ""
echo -e "  Frontend: ${BOLD}http://localhost:3000${RESET}"
echo -e "  Backend:  ${BOLD}http://localhost:8000/docs${RESET}"
echo ""
echo -e "Waiting for containers to be ready..."
sleep 8
echo ""
echo -e "${GREEN}Open ${BOLD}http://localhost:3000${RESET}${GREEN} in your browser.${RESET}"
echo ""
